### ISSUE TITLE
write data pulling functions for the connectomes of interest - xlsx

### ISSUE THREAD

**Issue by pauladkisson** [neurodata/connectocross#6]
for the connectomes listed in the readme (roughly, exact ones may change)
- want a simple, clear script to pull necessary graph + metadata from wherever it's hosted online 
- saves that data to the format specified in #1 

Note: Sub-issue of #2 

Specifically, focus on datasets stored as .xlsx files.

**Comment by pauladkisson** [comment]
# Deliverables
Functions (one for each dataset) that
1. pulls graph data from each of the sites listed that have .xlsx format (WormWiring, etc.)
2. pulls graph metadata from each of the sites listed that have .xlsx format (WormWiring, etc.)
3. saves data to format specified in #1

**Comment by bdpedigo** [comment]
note: it may not be possible to do this generally for all xlsx if that makes sense. i.e. some paper may store in xlsx in one way, another might do it differently. just pointing out that this will likely be dataset specific

**Comment by pauladkisson** [comment]
> note: it may not be possible to do this generally for all xlsx if that makes sense. i.e. some paper may store in xlsx in one way, another might do it differently. just pointing out that this will likely be dataset specific

Ok, I'll just to see how it goes then.

**Comment by bdpedigo** [comment]
need to spec out what kind of metadata you will have. also which connectomes specifically.
